# Generated by Django 2.2.16 on 2022-07-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220717_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='validation_code',
            new_name='confirmation_code',
        ),
    ]
